/** Jest manual mock — see setupTests.js */
const mockProjectsList = [
  {
    id: '1',
    title: 'Project A',
    description: 'Description A',
    status: 'Completed',
    image: 'image1.jpg',
    createdDate: '2024-01-15',
    tasks: [],
  },
  {
    id: '2',
    title: 'Project B',
    description: 'Description B',
    status: 'In Progress',
    image: 'image2.jpg',
    createdDate: '2024-02-10',
    tasks: [],
  },
  {
    id: '3',
    title: 'Project C',
    description: 'Description C',
    status: 'Planning',
    image: 'image3.jpg',
    createdDate: '2024-01-20',
    tasks: [],
  },
]

const defaultProject = {
  id: '1',
  title: 'Test Project',
  description: 'Test description',
  status: 'Planning',
  image: 'test.jpg',
  materials: [],
  pictures: [],
  videos: [],
  tasks: [],
  references: [],
}

export default {
  setUser: jest.fn(),
  setOnUnauthorized: jest.fn(),
  getProjects: jest.fn().mockResolvedValue({
    projects: mockProjectsList,
    pendingCollaborationRequests: [],
  }),
  getProject: jest.fn().mockResolvedValue({ ...defaultProject }),
  createProject: jest.fn().mockResolvedValue({ id: 'new', title: 'New' }),
  updateProject: jest.fn().mockResolvedValue({}),
  deleteProject: jest.fn().mockResolvedValue({}),
  deleteAccount: jest.fn().mockResolvedValue({}),
  updateProjectStatus: jest.fn().mockResolvedValue({}),
  addTask: jest.fn().mockResolvedValue({}),
  getTasks: jest.fn().mockResolvedValue([]),
  toggleTask: jest.fn().mockResolvedValue({}),
  addPicture: jest.fn().mockResolvedValue({}),
  addVideo: jest.fn().mockResolvedValue({}),
  addMaterial: jest.fn().mockResolvedValue({}),
  toggleMaterialPurchased: jest.fn().mockResolvedValue({}),
  addReference: jest.fn().mockResolvedValue({}),
  deletePicture: jest.fn().mockResolvedValue({}),
  getCollaborators: jest.fn().mockResolvedValue([]),
  addCollaborator: jest.fn().mockResolvedValue({}),
  removeCollaborator: jest.fn().mockResolvedValue({}),
  redeemInvite: jest.fn().mockResolvedValue({}),
  acceptCollaborationRequest: jest.fn().mockResolvedValue({}),
  declineCollaborationRequest: jest.fn().mockResolvedValue({}),
}
